### ISSUE TITLE
[QUESTION] What is the different?

### ISSUE THREAD

**Issue by mbrother2** [BlackHoleMonster/IP-BlackHole#6]
Hi,

Thank you for great blacklists!

What is the different between
ALL IPs:  https://blackhole.s-e-r-v-e-r.pw/blackhole
and
TODAY IPs: https://blackhole.s-e-r-v-e-r.pw/blackhole-today

It seems that the ALL IPs list is smaller than the TODAY IPs list, why?

**Comment by BlackHoleMonster** [comment]
Sometimes it could be when the system stuck and generate less ALL ip list than TODAY ip list.
ALL should be ALL ips, and TODAY should be only latest 24 hours.
